declare namespace NodeJS {
  interface ProcessEnv {
    PLAYWRIGHT_TEST_BASE_URL?: string;
    TEST_USER_NO_INSTITUTE_EMAIL?: string;
    TEST_USER_NO_INSTITUTE_PASSWORD?: string;
    TEST_USER_DIRECT_EMAIL?: string;
    TEST_USER_DIRECT_PASSWORD?: string;
    TEST_USER_ROLE_SELECTION_EMAIL?: string;
    TEST_USER_ROLE_SELECTION_PASSWORD?: string;
    TEST_USER_MULTI_INST_EMAIL?: string;
    TEST_USER_MULTI_INST_PASSWORD?: string;
    TEST_USER_MULTI_INST2_EMAIL?: string;
    TEST_USER_MULTI_INST2_PASSWORD?: string;
    TEST_USER_INVALID_PASSWORD_EMAIL?: string;
    TEST_USER_INVALID_PASSWORD?: string;
    TEST_USER_INVALID_EMAIL?: string;
    TEST_USER_INVALID_EMAIL_PASSWORD?: string;
    TEST_USER_MALFORMED_EMAIL?: string;
    TEST_USER_MALFORMED_EMAIL_PASSWORD?: string;
    CI?: string;
  }
}
